-- COMPREHENSIVE DATABASE FIELD FIX SCRIPT
-- Generated by system_field_audit.php on 2026-02-13
-- This script adds all missing fields identified in the system audit

-- === TICKETS TABLE FIXES ===
-- All ticket fields are already present according to our check

-- === CLIENTS TABLE FIXES ===
-- Add missing 'notes' field to clients table
ALTER TABLE clients ADD COLUMN notes TEXT;

-- === USERS TABLE FIXES ===
-- The users table has some structural differences from expected
-- Current structure shows: email, password, user_type, etc.
-- But our audit expected: username, password_hash, role, first_name, last_name, phone

-- First, let's check the current users table structure more carefully
-- Since the current table uses 'password' and 'user_type', we need to be careful
-- We'll add the missing fields that don't conflict

-- Add missing fields to users table (these appear to be missing)
ALTER TABLE users ADD COLUMN first_name CHARACTER VARYING(100);
ALTER TABLE users ADD COLUMN last_name CHARACTER VARYING(100); 
ALTER TABLE users ADD COLUMN phone CHARACTER VARYING(50);
ALTER TABLE users ADD COLUMN username CHARACTER VARYING(100);

-- Note: password_hash and role fields may not be needed since we have password and user_type
-- Let's verify what the application actually uses

-- === CHECK OTHER TABLES ===
-- Let's examine some of the undocumented tables to see if they need fields

-- Check assets table structure
\d assets

-- Check certificates table structure  
\d certificates

-- Check client_locations table structure
\d client_locations

-- === VERIFICATION QUERIES ===
-- Verify all fixes were applied

-- Check clients table
SELECT column_name, data_type, is_nullable 
FROM information_schema.columns 
WHERE table_name = 'clients' 
AND column_name = 'notes';

-- Check users table (show new fields)
SELECT column_name, data_type, is_nullable 
FROM information_schema.columns 
WHERE table_name = 'users' 
AND column_name IN ('first_name', 'last_name', 'phone', 'username');

-- Show all current columns in key tables
SELECT table_name, COUNT(*) as column_count
FROM information_schema.columns 
WHERE table_name IN ('tickets', 'clients', 'users', 'staff_profiles', 'contracts')
GROUP BY table_name
ORDER BY table_name;

-- Final verification of tickets table (our main concern)
SELECT column_name, data_type, character_maximum_length, is_nullable
FROM information_schema.columns 
WHERE table_name = 'tickets' 
AND column_name IN ('requested_by', 'requested_by_email', 'csr_sn', 'pi_number')
ORDER BY ordinal_position;